import PptxGenJS from 'pptxgenjs';
import { PptxViewer, RECOMMENDED_ZIP_LIMITS } from '@aiden0z/pptx-renderer/browser';

const template=document.createElement('template');
template.innerHTML=`<style>
:host{display:block;min-height:360px;color:#111;font-family:Arial,"Microsoft YaHei",sans-serif}
:host([data-css-fullscreen]){position:fixed;inset:0;z-index:2147483647;width:100vw;height:100vh;background:#111}
*{box-sizing:border-box}.card{height:100%;min-height:360px;background:#fff;border:1px solid #d8dadd;border-radius:12px;overflow:hidden;display:grid;grid-template-rows:auto 1fr;box-shadow:0 3px 18px rgba(0,0,0,.05)}
:host([data-css-fullscreen]) .card,:host(:fullscreen) .card{position:relative;border:0;border-radius:0;height:100vh;grid-template-rows:1fr}:host([data-css-fullscreen]) .bar,:host(:fullscreen) .bar{position:absolute;top:0;left:0;right:0;z-index:10;background:rgba(250,250,250,.94);backdrop-filter:blur(6px)}.bar{display:flex;align-items:center;justify-content:space-between;gap:6px;padding:4px 6px;background:#fafafa;border-bottom:1px solid #ddd;transition:opacity .18s ease,transform .18s ease}
.meta{font-size:10px;color:#777;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:52vw}:host([chrome="minimal"]) .meta{display:none}:host([chrome="none"]) .bar{display:none}:host([chrome="none"]) .card{grid-template-rows:1fr}:host([chrome="none"]) .stage{max-width:calc((100vh - 16px)*16/9)}.nav{display:flex;align-items:center;gap:4px}.nav button{display:inline-grid;place-items:center;width:28px;height:28px;border:1px solid #c7c7c7;background:#fff;padding:0;border-radius:7px;cursor:pointer;font-size:15px;line-height:1}.nav button:hover{background:#f1f2f3}.nav button:disabled{opacity:.35}
.page{min-width:44px;text-align:center;font-size:11px;font-weight:700}.shell{min-height:0;background:#d7d9dc;display:flex;align-items:center;justify-content:center;padding:8px;overflow:hidden}
.stage{position:relative;width:100%;max-width:calc((100vh - 78px)*16/9);aspect-ratio:16/9;background:#fff;overflow:hidden;box-shadow:0 2px 14px rgba(0,0,0,.18)}
:host([data-css-fullscreen]) .stage,:host(:fullscreen) .stage{max-width:calc(100vh*16/9)}.viewer{position:absolute;inset:0;width:100%;height:100%;overflow:hidden}
.loading{position:absolute;inset:0;display:grid;place-items:center;background:#fff;color:#666;font-size:13px;z-index:5}.loading[hidden]{display:none}:host([data-controls-hidden]) .bar{opacity:0;transform:translateY(-100%);pointer-events:none}:host([data-controls-hidden]) .stage{max-width:calc(100vh*16/9)}
</style>
<section class="card"><div class="bar"><div><strong>Presentation</strong><div class="meta"></div></div><div class="nav"><button class="prev" title="Previous slide" aria-label="Previous slide">‹</button><span class="page">0 / 0</span><button class="next" title="Next slide" aria-label="Next slide">›</button><button class="download" title="Download PPTX" aria-label="Download PPTX">⬇️</button><button class="full" title="Fullscreen" aria-label="Fullscreen">⛶</button></div></div>
<div class="shell"><div class="stage"><div class="viewer"></div><div class="loading">Loading presentation…</div></div></div></section>`;

let activePresentation=null;

function normalizeBuildResult(result){
  if(result instanceof ArrayBuffer)return {bytes:result,meta:{}};
  if(result?.bytes instanceof ArrayBuffer)return {bytes:result.bytes,meta:result};
  throw new TypeError('buildDeck() must return ArrayBuffer or { bytes: ArrayBuffer, ...metadata }');
}

class PptxPresentation extends HTMLElement{
  static get observedAttributes(){return['src','chrome','current-slide','initial-slide']}
  constructor(){super();this.attachShadow({mode:'open'}).append(template.content.cloneNode(true));this.$=s=>this.shadowRoot.querySelector(s);this.context=undefined;this._buildMeta={};this._loadSeq=0;this._viewer=null;this._current=0;this._total=0;this._wheel=0;this._wheelLock=0;this._bytes=null;this._controlsTimer=0;this._clickTimer=0;this._wakeOnly=false;this._onKey=e=>this.#onKey(e);this._onPointerMove=e=>this.#onPointerMove(e);this._onPointerDown=()=>{this.activate('pointer');this._wakeOnly=this.hasAttribute('data-controls-hidden');this.#showControls()};this._onFocusIn=()=>this.activate('focus');this._onFullscreenChange=()=>{if(document.fullscreenElement===this)this.activate('fullscreen');else{this.removeAttribute('data-controls-hidden');clearTimeout(this._controlsTimer)}}}
  connectedCallback(){this.$('.prev').onclick=()=>this.previous();this.$('.next').onclick=()=>this.next();this.$('.download').onclick=()=>this.download();this.$('.full').onclick=()=>this.toggleFullscreen();this.$('.stage').onclick=e=>{if(this._wakeOnly){this._wakeOnly=false;return}clearTimeout(this._clickTimer);const x=e.clientX;this._clickTimer=setTimeout(()=>{const r=this.$('.stage').getBoundingClientRect();this.goTo(this._current+(x-r.left<r.width/2?-1:1))},220)};this.$('.stage').ondblclick=e=>{e.preventDefault();clearTimeout(this._clickTimer);this.toggleFullscreen()};this.$('.stage').addEventListener('wheel',e=>this.#onWheel(e),{passive:false});window.addEventListener('keydown',this._onKey);document.addEventListener('fullscreenchange',this._onFullscreenChange);this.addEventListener('pointermove',this._onPointerMove,{passive:true});this.addEventListener('pointerdown',this._onPointerDown,{passive:true});this.addEventListener('focusin',this._onFocusIn);if(this.src)this.load(this.src)}
  disconnectedCallback(){window.removeEventListener('keydown',this._onKey);document.removeEventListener('fullscreenchange',this._onFullscreenChange);this.removeEventListener('pointermove',this._onPointerMove);this.removeEventListener('pointerdown',this._onPointerDown);this.removeEventListener('focusin',this._onFocusIn);if(this.active)this.deactivate('disconnect');clearTimeout(this._controlsTimer);clearTimeout(this._clickTimer)}
  attributeChangedCallback(name,oldValue,newValue){if(name==='src'&&oldValue!==newValue&&this.isConnected&&newValue)this.load(newValue,{preserveSlide:false});if(name==='chrome'&&!['normal','minimal','none'].includes(newValue||'normal'))this.setAttribute('chrome','normal');else if(name==='chrome'&&oldValue!==newValue&&this.isConnected)this.#emitStateChange('chrome');if(name==='current-slide'&&oldValue!==newValue&&this.isConnected&&this._viewer){const n=this.#slideAttr(newValue,this._current+1);this.goTo(n-1)}}
  get src(){return this.getAttribute('src')||''} set src(v){this.setAttribute('src',v)}
  get currentSlide(){return this._current} get slideCount(){return this._total} get ready(){return !!this._viewer} get active(){return activePresentation===this} get chrome(){return this.getAttribute('chrome')||'normal'} set chrome(v){this.setAttribute('chrome',v)} get currentSlideNumber(){return this._current+1} set currentSlideNumber(v){this.setAttribute('current-slide',String(v))} get initialSlide(){return this.#slideAttr(this.getAttribute('initial-slide'),1)} set initialSlide(v){this.setAttribute('initial-slide',String(v))}
  activate(reason='programmatic'){if(activePresentation===this)return false;const previous=activePresentation;activePresentation=this;if(previous?.isConnected)previous.dispatchEvent(new CustomEvent('activechange',{detail:{active:false,reason:'superseded'}}));this.dispatchEvent(new CustomEvent('activechange',{detail:{active:true,reason}}));return true}
  deactivate(reason='programmatic'){if(activePresentation!==this)return false;activePresentation=null;this.dispatchEvent(new CustomEvent('activechange',{detail:{active:false,reason}}));return true}
  getState(){return {schema:'pptx-presentation/state-v1',src:this.src,slide:this._total?this._current+1:this.#slideAttr(this.getAttribute('current-slide'),this.initialSlide),chrome:this.chrome,buildRevision:this._buildMeta?.revision??null}}
  async restoreState(state,{restoreSource=false}={}){if(!state||typeof state!=='object'||state.schema!=='pptx-presentation/state-v1')throw new TypeError('invalid pptx-presentation state');const slide=this.#slideAttr(state.slide,1);if(state.chrome&&['normal','minimal','none'].includes(state.chrome))this.chrome=state.chrome;if(restoreSource&&state.src&&state.src!==this.src){this.setAttribute('current-slide',String(slide));this.src=state.src;return}if(this._viewer)await this.goTo(slide-1);else this.setAttribute('current-slide',String(slide))}
  download(filename){if(!this._bytes)return;const fallback=(this.src.split('/').pop()||'presentation').replace(/\.(m?js|ts)$/i,'')||'presentation';const suggested=this._buildMeta?.filename||this._buildMeta?.title;const stem=(suggested||fallback).toString().replace(/[\\/:*?"<>|]+/g,'-').replace(/\.pptx$/i,'').trim()||'presentation';const name=filename||`${stem}.pptx`;const blob=new Blob([this._bytes],{type:'application/vnd.openxmlformats-officedocument.presentationml.presentation'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);this.dispatchEvent(new CustomEvent('download',{detail:{src:this.src,filename:name}}))}
  async refresh({preserveSlide=true}={}){if(this.src)return this.load(this.src,{preserveSlide})}
  async load(src,{preserveSlide=true}={}){
    const seq=++this._loadSeq,started=performance.now();const requested=preserveSlide&&this._total?this._current+1:this.#slideAttr(this.getAttribute('current-slide'),this.initialSlide);this._viewer=null;this._current=0;this._total=0;this._bytes=null;this._buildMeta={};this.$('.viewer').replaceChildren();this.$('.loading').hidden=false;this.$('.loading').textContent='Loading presentation…';this.#sync();
    try{
      const absoluteSrc=new URL(src,document.baseURI).href;const buildStart=performance.now();const mod=await import(absoluteSrc);
      if(typeof mod.buildDeck!=='function')throw new Error(`${src} must export buildDeck(runtime, context)`);
      const result=normalizeBuildResult(await mod.buildDeck(PptxGenJS,this.context));const buildMs=performance.now()-buildStart;if(seq!==this._loadSeq)return;this._bytes=result.bytes;this._buildMeta=result.meta||{};
      const openStart=performance.now();this._viewer=await PptxViewer.open(result.bytes,this.$('.viewer'),{zipLimits:RECOMMENDED_ZIP_LIMITS,renderMode:'slide',fitMode:'contain'});if(seq!==this._loadSeq)return;
      this._total=this._viewer.slideCount;this._current=Math.max(0,Math.min(this._total-1,requested-1));if(this._current)await this._viewer.renderSlide(this._current);this.#syncCurrentSlideAttribute();this.$('.meta').textContent=this._buildMeta?.title||src;this.$('.meta').title=`${src} · build ${buildMs.toFixed(0)} ms · open ${(performance.now()-openStart).toFixed(0)} ms · ready ${(performance.now()-started).toFixed(0)} ms`;this.$('.loading').hidden=true;this.#sync();
      this.dispatchEvent(new CustomEvent('ready',{detail:{src,slideCount:this._total,build:result.meta,state:this.getState()}}));this.#emitStateChange('ready');
    }catch(error){if(seq!==this._loadSeq)return;this.$('.loading').hidden=false;this.$('.loading').textContent=`Failed: ${error.message}`;this.dispatchEvent(new CustomEvent('error',{detail:{src,error}}))}
  }
  async goTo(index){if(!this._viewer||!this._total)return;const n=Math.max(0,Math.min(this._total-1,index));if(n===this._current&&this.$('.viewer').childElementCount){this.#syncCurrentSlideAttribute();return}await this._viewer.renderSlide(n);this._current=n;this.#syncCurrentSlideAttribute();this.#sync();this.dispatchEvent(new CustomEvent('slidechange',{detail:{index:n,slide:n+1}}));this.#emitStateChange('slide')}
  next(){return this.goTo(this._current+1)} previous(){return this.goTo(this._current-1)}
  async toggleFullscreen(){this.activate('fullscreen');if(this.hasAttribute('data-css-fullscreen')){this.removeAttribute('data-css-fullscreen');this.removeAttribute('data-controls-hidden');clearTimeout(this._controlsTimer);this.$('.full').textContent='⛶';this.$('.full').title='Fullscreen';return}if(document.fullscreenElement){try{await document.exitFullscreen()}catch{};this.$('.full').textContent='⛶';this.$('.full').title='Fullscreen';return}const request=this.requestFullscreen||this.webkitRequestFullscreen;if(request){try{await request.call(this);this.$('.full').textContent='↙';this.$('.full').title='Exit fullscreen';this.#showControls();return}catch{}}this.setAttribute('data-css-fullscreen','');this.$('.full').textContent='↙';this.$('.full').title='Exit fullscreen';this.#showControls()}
  #slideAttr(value,fallback){const n=Number.parseInt(value,10);return Number.isFinite(n)&&n>=1?n:fallback}
  #emitStateChange(reason){this.dispatchEvent(new CustomEvent('statechange',{detail:{reason,state:this.getState()}}))}
  #syncCurrentSlideAttribute(){const value=String(this._current+1);if(this.getAttribute('current-slide')!==value)this.setAttribute('current-slide',value)}
  #isPresenting(){return document.fullscreenElement===this||this.hasAttribute('data-css-fullscreen')}
  #showControls(){if(this.chrome==='none')return;this.removeAttribute('data-controls-hidden');clearTimeout(this._controlsTimer);const presenting=this.#isPresenting();if(presenting)this._controlsTimer=setTimeout(()=>this.setAttribute('data-controls-hidden',''),1800)}
  #onPointerMove(e){if(!this.#isPresenting()||this.chrome==='none')return;const r=this.getBoundingClientRect();if(e.clientY-r.top<=64)this.#showControls()}
  #sync(){this.$('.page').textContent=`${this._total?this._current+1:0} / ${this._total}`;this.$('.prev').disabled=!this._total||this._current<=0;this.$('.next').disabled=!this._total||this._current>=this._total-1;this.$('.download').disabled=!this._bytes}
  #onWheel(e){if(e.ctrlKey||e.metaKey||!this._viewer)return;e.preventDefault();const now=performance.now();if(now<this._wheelLock)return;this._wheel+=Math.abs(e.deltaY)>=Math.abs(e.deltaX)?e.deltaY:e.deltaX;if(Math.abs(this._wheel)>=72){const d=this._wheel>0?1:-1;this._wheel=0;this._wheelLock=now+320;this.goTo(this._current+d)}}
  #onKey(e){if(!this.active&&document.fullscreenElement!==this)return;this.#showControls();let handled=true;if(e.key==='ArrowLeft'||e.key==='PageUp')this.previous();else if(e.key==='ArrowRight'||e.key==='PageDown'||e.key===' ')this.next();else if(e.key==='Home')this.goTo(0);else if(e.key==='End')this.goTo(this._total-1);else if(e.key.toLowerCase()==='f')this.toggleFullscreen();else handled=false;if(handled)e.preventDefault()}
}
if(!customElements.get('pptx-presentation'))customElements.define('pptx-presentation',PptxPresentation);
export {PptxPresentation};
