#!/bin/sh
set -eu

operation=${1:-}
[ "$operation" = get ] || exit 0

protocol=
host=
while IFS='=' read -r key value; do
  case "$key" in
    protocol) protocol=$value ;;
    host) host=$value ;;
  esac
done
[ -n "$host" ] || exit 0

netrc=${NETRC:-${HOME:-/root}/.netrc}
[ -r "$netrc" ] || exit 0
awk -v wanted="$host" '
  $1 == "machine" {
    active = ($2 == wanted)
    login = ""
    password = ""
  }
  active && $1 == "login" { login = $2 }
  active && $1 == "password" { password = $2 }
  active && login != "" && password != "" {
    print "username=" login
    print "password=" password
    exit
  }
' "$netrc"
